language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js: "12"

git:
  depth: 10
  submodules: false

branches:
  only:
    - master

sudo: false

env:
  - CC=clang CXX=clang++ npm_config_clang=1

install:
  - npm run prepare
  - npm install

script:
  - npm run lint
  - npm run test
