language: node_js

sudo: false

node_js: 12

env:
  - CC=clang CXX=clang++

script: npm run ci

git:
  depth: 10

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
