language: node_js

node_js:
- 10
- 12

os:
- osx
- linux

compiler: clang

before_install:
- git submodule update --init --recursive

branches:
  only:
  - master
  - /^v.*$/

deploy:
  provider: script
  script: npm run prebuild && npm run prebuild:upload -u ${PREBUILD_UPLOAD}
  skip_cleanup: true
  on:
    all_branches: true
    tags: true

env:
  CC: clang
  CXX: clang++
  global:
    secure: Jn0t44EE07oEY0eUqRAFcbVwf34hAHx6pmWnDHJRBN9XcH3eHo0DFA32TGtbgYy90dChgdKYLWCwbeZzv1nxJiAy/CItCRcfpc4BJAkvxmtoPiFPpkqJl00CRgO+xGselNPgRhdeHeIEYFUcKAzAX7vxB85YTTys3gWV5Zb1SAQ=
