name: build
on: push
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      CFLAGS: -g -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined --coverage
      CXXFLAGS: -g -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined --coverage
      LDFLAGS: -fsanitize=address -fsanitize=undefined
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: cmake .
      - run: cmake --build .
      - run: atom/atom-tests
      - run: geninfo . -o coverage.info
      - run: genhtml coverage.info coverage-html
